// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcndmusgtrcgszsikmyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbmRtdXNndHJjZ3N6c2lrbXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1MDg2NDQsImV4cCI6MjA5MDA4NDY0NH0.w0UkqoO82o0g2IWoq8x_E0Gm9znIpUpRUV9INVSn4hk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});